// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract NFTRDX is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter private _tokenIdCounter;

    string[] ipfsURI = [
        "https://gateway.pinata.cloud/ipfs/QmSvdYyHzumKCaMdfBmnVV42KDCy8T8JG8BKGibX7nzegH",
        "https://gateway.pinata.cloud/ipfs/Qmc5yYQFg2h5JXtBEXReL268N3EraykXJC3JVwA4RvKpcm",
        "https://gateway.pinata.cloud/ipfs/QmWjvQCfotAvbjhMtqjVR41UKYg8xdasqLqkcWDyjTRhah",
        "https://gateway.pinata.cloud/ipfs/QmToS8LdnNgtSgeDBpQccgRXNoq17duf6RzJk2kZ9ie9JD",
        "https://gateway.pinata.cloud/ipfs/QmSWjFttm9qpRSsyWgdBmr9xDh2RNuNBzGinnHwZqk5yyL"
    ];

    uint256 lastTimeStamp;
    uint256 interval;

    constructor(uint _interval) ERC721("NFTRDX", "RDX") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = _tokenIdCounter.current() - 1;
        bool done;
        if (pokeStage(tokenId) >= 4) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = _tokenIdCounter.current() - 1;
            evolvePoke(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public  {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, ipfsURI[0]);
    }

    function evolvePoke(uint256 _tokenId) public {
        if(pokeStage(_tokenId) >= 4){return;}
        
        uint256 newVal = pokeStage(_tokenId) + 1;
        // store the new URI
        string memory newUri = ipfsURI[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function pokeStage(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        
        if (compareStrings(_uri, ipfsURI[0])) {
            return 0;
        }
        
        if (
            compareStrings(_uri, ipfsURI[1]) 
        ) {
            return 1;
        }
        if (
            compareStrings(_uri, ipfsURI[2]) 
        ) {
            return 2;
        }
        if (
            compareStrings(_uri, ipfsURI[3]) 
        ) {
            return 3;
        }
        
        return 4;
    }

     // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions are overrides required by Solidity.

    function _burn(uint256 tokenId) internal override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }

    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}
